#ifdef CPLX
#define SCALAR complex(dpc)
#define Zmatvec_nloc zmatvec_nloc
#define Zmatvec_nlocB_1D zmatvec_nlocB_1D
#define Zmatvec_nloc_kbdotsB_1D zmatvec_nloc_kbdotsB_1D 
#define Zmatvec_nloc_kbdotsB_kpt_1D zmatvec_nloc_kbdotsB_kpt_1D 
#define Zmatvec_ke zmatvec_ke
#define Zmatvec_ke_new zmatvec_ke_new
#define Zmatvec_ke_kpt zmatvec_ke_kpt
#define Zmatvec1 zmatvec1
#define ZmatvecB zmatvecB
#define Zmatvec_ke_1D zmatvec_ke_1D
#define Zmatvec_ke_kpt_1D zmatvec_ke_kpt_1D
#define Zlaplacianmv1 zlaplacianmv1
#define Zdiagonalmv1 zdiagonalmv1
#define Zmatvec_diagonal zmatvec_diagonal
#define Zcopy zcopy
#define Zscal zscal
#define Zaxpy zaxpy
#define Zgemm zgemm
#define Zmygemm zmygemm
#define Zlacpy zlacpy
#define Zgemv zgemv
#define Zdot zdotc
#define Zpsum zpsum
#define Zbuff_lap_comm zbuff_lap_comm
#define Zbuff_lap_pack zbuff_lap_pack 
#define Zbuff_lap_pack_and_comm zbuff_lap_pack_and_comm
#define Zbuffer_lap_unpack zbuffer_lap_unpack
#define Zbuff_nloc_allreduce zbuff_nloc_allreduce
#define Zbuffer_module zbuffer_module
#define Zzero zzero
#define Zone zone
#define Zwvec zwvec
#define Conjg 'C'
#define MPI_DOUBLE_SCALAR MPI_DOUBLE_COMPLEX
#else
#define SCALAR real(dp)
#define Zmatvec_nloc matvec_nloc
#define Zmatvec_nlocB_1D matvec_nlocB_1D
#define Zmatvec_nlocB_kpt_1D matvec_nlocB_kpt_1D
#define Zmatvec_nloc_kbdotsB_1D matvec_nloc_kbdotsB_1D 
#define Zmatvec_nloc_kbdotsB_kpt_1D matvec_nloc_kbdotsB_kpt_1D 
#define Zmatvec_ke matvec_ke
#define Zmatvec_ke_new matvec_ke_new
#define Zmatvec_ke_kpt matvec_ke_kpt
#define Zmatvec1 matvec1
#define ZmatvecB matvecB
#define Zmatvec_ke_1D matvec_ke_1D
#define Zmatvec_ke_kpt_1D matvec_ke_kpt_1D
#define Zlaplacianmv1 laplacianmv1
#define Zdiagonalmv1 diagonalmv1
#define Zmatvec_diagonal matvec_diagonal
#define Zcopy dcopy
#define Zscal dscal
#define Zaxpy daxpy
#define Zgemm dgemm
#define Zmygemm mygemm
#define Zlacpy dlacpy
#define Zgemv dgemv
#define Zdot ddot
#define Zpsum psum
#define Zbuff_lap_comm buff_lap_comm
#define Zbuff_lap_pack buff_lap_pack 
#define Zbuff_lap_pack_and_comm buff_lap_pack_and_comm
#define Zbuffer_lap_unpack buffer_lap_unpack
#define Zbuff_nloc_allreduce buff_nloc_allreduce
#define Zbuffer_module buffer_module
#define Zzero zero
#define Zone one
#define Zwvec dwvec
#define Conjg 'T'
#define MPI_DOUBLE_SCALAR MPI_DOUBLE_PRECISION
#endif
